version: '3.5'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_ENV: "dev"
      POSTGRES_URI: "postgresql+asyncpg://admin:pass@postgres:5432/lms"
      POSTGRES_SCHEME: "public"
      RMQ_URI: "amqp://admin:pass@rmq:5672"
      SHOW_TRACEBACK_IN_RESPONSE: "true"
      LOGGING_LEVEL: "10"
      RELOAD: "true"
      FASTAPI_LOGGING_LEVEL: "10"
    networks:
      - base
    ports:
      - "5005:5005"
    volumes:
      - ./src:/app/src
    restart: always

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "pass"
    ports:
      - "5432:5432"
    networks:
      - base
    restart: unless-stopped

  rmq:
    image: "rabbitmq:3.6-management-alpine"
    hostname: "rabbitmq-host"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "pass"
    networks:
      - base
    restart: unless-stopped

networks:
  base:
    driver: bridge
