version: '3.9'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: "./docker.env"
    networks:
      - base
    ports:
      - "5005:5005"
    volumes:
      - ./src:/app/src
    restart: always

  postgres:
    image: postgres
    env_file: "./docker.env"
    ports:
      - "5432:5432"
    networks:
      - base
    restart: unless-stopped

  rmq:
    image: "rabbitmq:3.6-management-alpine"
    hostname: "rabbitmq-host"
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file: "./docker.env"
    networks:
      - base
    restart: unless-stopped

networks:
  base:
    driver: bridge
